### ISSUE TITLE
unable to login: 401 Invalid Intergration key in request credentials

### ISSUE THREAD

**Issue by JM-AIV** [duosecurity/duo_client_python#104]
hi guys,

I've tried to get this working but I'm unable to do so. could you please help me?
offcourse I double checked the login!

Traceback (most recent call last):
  File "duotest.py", line 25, in <module>
    users = admin_api.get_users()
  File "/home/admin/.local/lib/python3.6/site-packages/duo_client/admin.py", line 527, in get_users
    return list(self.get_users_iterator())
  File "/home/admin/.local/lib/python3.6/site-packages/duo_client/client.py", line 400, in json_paging_api_call
    (objects, metadata) = self.parse_json_response_and_metadata(response, data)
  File "/home/admin/.local/lib/python3.6/site-packages/duo_client/client.py", line 438, in parse_json_response_and_metadata
    data['message'],
  File "/home/admin/.local/lib/python3.6/site-packages/duo_client/client.py", line 422, in raise_error
    raise error
RuntimeError: Received 401 Invalid integration key in request credentials

**Comment by JM-AIV** [comment]
sorry guys, i was using the wrong intergration application. case closed!
