### ISSUE TITLE
Invalid Integration Key

### ISSUE THREAD

**Issue by gogskrish** [duosecurity/duo_client_python#127]
I have application created and it has integration key and security key. However it shows Invalid Integration key.

Traceback (most recent call last):
  File "examples/report_auths_by_country.py", line 25, in <module>
    logs = admin_api.get_authentication_log()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/duo_client/admin.py", line 452, in get_authentication_log
    response = self.json_api_call(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/duo_client/client.py", line 383, in json_api_call
    return self.parse_json_response(response, data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/duo_client/client.py", line 409, in parse_json_response
    (response, metadata) = self.parse_json_response_and_metadata(response, data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/duo_client/client.py", line 436, in parse_json_response_and_metadata
    raise_error('Received %s %s' % (
  File "/home/ubuntu/.local/lib/python3.8/site-packages/duo_client/client.py", line 422, in raise_error
    raise error
RuntimeError: Received 401 Invalid integration key in request credentials

**Comment by BradleyHiggins** [comment]
Duo has different types of integration keys. One integration key type is used for authenticating users, and a separate ikey type is used to make Admin API calls.

Please make sure you're using an Admin API ikey / skey combo when calling Admin API endpoints off of the admin_api object.

Please reach out to Duo Support for further help with this issue.

Thanks for using Duo!
