### ISSUE TITLE
pip install now fails with error about six module

### ISSUE THREAD

**Issue by cwalkatron** [duosecurity/duo_client_python#15]
In a fresh virtualenv (python 2.7.5 on Linux), this works:

`pip install git+https://github.com/duosecurity/duo_client_python@369fe43b8b09bf5948d88eaf0e1e1c78b584044a`

while this doesn't:

`pip install git+https://github.com/duosecurity/duo_client_python`

Here's the `pip.log`:

```
------------------------------------------------------------
/tmp/pyenv/bin/pip run on Tue Sep  1 13:46:51 2015
Downloading/unpacking git+https://github.com/duosecurity/duo_client_python@d33f0f7d6f53b40939dd8edc908832922681fa82

  Cloning https://github.com/duosecurity/duo_client_python (to d33f0f7d6f53b40939dd8edc908832922681fa82) to ./pip-Mq6Yiv-build

  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q https://github.com/duosecurity/duo_client_python /tmp/pip-Mq6Yiv-build
  Running command /usr/bin/git show-ref
  d37822ed4740e1fd9dd52bd58a3c7abaee91dbb1 refs/heads/master
  d37822ed4740e1fd9dd52bd58a3c7abaee91dbb1 refs/remotes/origin/HEAD
  d37822ed4740e1fd9dd52bd58a3c7abaee91dbb1 refs/remotes/origin/master
  Could not find a tag or branch 'd33f0f7d6f53b40939dd8edc908832922681fa82', assuming commit.

  Running command /usr/bin/git rev-parse HEAD
  d37822ed4740e1fd9dd52bd58a3c7abaee91dbb1
  Running command /usr/bin/git checkout -q d33f0f7d6f53b40939dd8edc908832922681fa82
  Running setup.py egg_info for package from git+https://github.com/duosecurity/duo_client_python@d33f0f7d6f53b40939dd8edc908832922681fa82

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/tmp/pip-Mq6Yiv-build/setup.py", line 4, in <module>

        from duo_client import __version__

      File "duo_client/__init__.py", line 2, in <module>

        from .accounts import Accounts

      File "duo_client/accounts.py", line 7, in <module>

        from . import client

      File "duo_client/client.py", line 6, in <module>

        import six

    ImportError: No module named six

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-Mq6Yiv-build/setup.py", line 4, in <module>

    from duo_client import __version__

  File "duo_client/__init__.py", line 2, in <module>

    from .accounts import Accounts

  File "duo_client/accounts.py", line 7, in <module>

    from . import client

  File "duo_client/client.py", line 6, in <module>

    import six

ImportError: No module named six

----------------------------------------

Cleaning up...

Command python setup.py egg_info failed with error code 1 in /tmp/pip-Mq6Yiv-build

Exception information:
Traceback (most recent call last):
  File "/tmp/pyenv/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/tmp/pyenv/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/pyenv/lib/python2.7/site-packages/pip/req.py", line 1134, in prepare_files
    req_to_install.run_egg_info()
  File "/tmp/pyenv/lib/python2.7/site-packages/pip/req.py", line 259, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/tmp/pyenv/lib/python2.7/site-packages/pip/util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-Mq6Yiv-build
 ```

**Comment by mschwager** [comment]
Thanks for the heads up! There will be a fix out shortly :)

**Comment by mschwager** [comment]
Ok, I've pushed a commit that should fix it (https://github.com/duosecurity/duo_client_python/commit/5ed1bb39e86e4ed58be3bda4a9947933b4a7fb9f). Can you confirm?

**Comment by cwalkatron** [comment]
Works great, thanks!
